################################################################
#
# DOOM macOS Port Makefile
# Builds DOOM for macOS using SDL2
#
# Usage: make -f Makefile.macos
#
################################################################

CC = clang

# Compiler flags
CFLAGS = -g -O2 -fPIC
CFLAGS += -DNORMALUNIX -DMACOS
CFLAGS += $(shell pkg-config --cflags sdl2)

# Linker flags
LDFLAGS = $(shell pkg-config --libs sdl2)
LDFLAGS += -lm

# Output directory for object files
O = macos

# Source directory
S = linuxdoom-1.10

# Object files list
OBJS = \
	$(O)/doomdef.o \
	$(O)/doomstat.o \
	$(O)/dstrings.o \
	$(O)/i_system.o \
	$(O)/i_sound_sdl.o \
	$(O)/i_video_sdl.o \
	$(O)/tables.o \
	$(O)/f_finale.o \
	$(O)/f_wipe.o \
	$(O)/d_main.o \
	$(O)/d_items.o \
	$(O)/g_game.o \
	$(O)/m_menu.o \
	$(O)/m_misc.o \
	$(O)/m_argv.o \
	$(O)/m_bbox.o \
	$(O)/m_fixed.o \
	$(O)/m_swap.o \
	$(O)/m_cheat.o \
	$(O)/m_random.o \
	$(O)/am_map.o \
	$(O)/p_ceilng.o \
	$(O)/p_doors.o \
	$(O)/p_enemy.o \
	$(O)/p_floor.o \
	$(O)/p_inter.o \
	$(O)/p_lights.o \
	$(O)/p_map.o \
	$(O)/p_maputl.o \
	$(O)/p_plats.o \
	$(O)/p_pspr.o \
	$(O)/p_setup.o \
	$(O)/p_sight.o \
	$(O)/p_spec.o \
	$(O)/p_switch.o \
	$(O)/p_mobj.o \
	$(O)/p_telept.o \
	$(O)/p_tick.o \
	$(O)/p_saveg.o \
	$(O)/p_user.o \
	$(O)/r_bsp.o \
	$(O)/r_data.o \
	$(O)/r_draw.o \
	$(O)/r_main.o \
	$(O)/r_plane.o \
	$(O)/r_segs.o \
	$(O)/r_sky.o \
	$(O)/r_things.o \
	$(O)/w_wad.o \
	$(O)/wi_stuff.o \
	$(O)/v_video.o \
	$(O)/st_lib.o \
	$(O)/st_stuff.o \
	$(O)/hu_stuff.o \
	$(O)/hu_lib.o \
	$(O)/s_sound.o \
	$(O)/z_zone.o \
	$(O)/info.o \
	$(O)/sounds.o

# Default target
all: $(O) $(O)/doom

# Create output directory
$(O):
	mkdir -p $(O)

# Main executable
$(O)/doom: $(OBJS) $(O)/i_main.o
	$(CC) $(CFLAGS) $(LDFLAGS) $(OBJS) $(O)/i_main.o -o $(O)/doom

# Compile rule
$(O)/%.o: $(S)/%.c
	$(CC) $(CFLAGS) -I$(S) -c $< -o $@

# Clean up
clean:
	rm -rf $(O)

# Info
info:
	@echo "DOOM macOS Port Build Configuration"
	@echo "===================================="
	@echo "CC: $(CC)"
	@echo "CFLAGS: $(CFLAGS)"
	@echo "LDFLAGS: $(LDFLAGS)"
	@echo ""
	@echo "Build targets:"
	@echo "  make -f Makefile.macos        Build DOOM"
	@echo "  make -f Makefile.macos clean  Clean build artifacts"
	@echo "  make -f Makefile.macos info   Show this information"
	@echo ""
	@echo "Usage:"
	@echo "  ./macos/doom -iwad DOOM.WAD"

.PHONY: all clean info
